test_rails_app/config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :courses
  root to: 'home#all_students'
  get '/hello', to: 'home#hello'
  get '/students', to: 'home#students'
  get '/all_students', to: 'home#all_students'
end

test_rails_app/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= ::User.new
    if user.is_admin?
      can :manage, Course
    else
      can :read, Course
    end
  end
end

test_rails_app/app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

test_rails_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

test_rails_app/app/models/course.rb
class Course < ApplicationRecord
  after_create :do_hard_work

  def do_hard_work
    ::HardWorker.perform_async(self.id)
  end
end

test_rails_app/app/models/group.rb
class Group < ApplicationRecord
  has_many :students
end

test_rails_app/app/models/student.rb
class Student < ApplicationRecord
  TOP_STUDENTS_NUMBER = 2
  REQUIRED_CREDITS = 240

  attr_accessor :credits

  belongs_to :group

  validates :avg_rating, numericality: { greater_than: 0, less_than_or_equal_to: 100 }
  validates :first_name, :last_name, presence: true

  before_validation :do_something_else
  before_create :do_something
  before_save :calc_has_stipend

  def full_name
    "#{first_name} #{last_name}"
  end

  def is_enough_credits?
    self.credits >= REQUIRED_CREDITS
  end

  private
  def do_something
  end

  def do_something_else
  end

  def calc_has_stipend
    self.has_stipend = ::Student.where('avg_rating > ?', self.avg_rating).count < TOP_STUDENTS_NUMBER
  end
end

test_rails_app/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
end

test_rails_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :set_locale

  def set_locale
    ::I18n.locale = params[:locale]
  end
end

test_rails_app/app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.accessible_by(current_ability)
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    respond_to do |format|
      format.html { }
      format.json {
        render json: @course, serializer: ::CourseSerializer
      }
    end
  end

  # GET /courses/new
  def new
    @course = Course.new
    authorize! :create, @course
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name)
    end
end

test_rails_app/app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
    render json: {ok: true, name: params[:name]}
  end

  def hello
  end

  def students
    @students = ::Student.all
    students_arr = @students.map do |s|
      {full_name: s.full_name}
    end
    logger.info "students_arr: #{students_arr}"
    render json: students_arr
  end

  def all_students
    @students = ::Student.all
  end
end

test_rails_app/app/helpers/application_helper.rb
module ApplicationHelper
end

test_rails_app/app/helpers/courses_helper.rb
module CoursesHelper
end

test_rails_app/app/views/courses/_form.html.erb
<%= form_for(course) do |f| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  Name: <%= f.text_field :name %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

test_rails_app/app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

test_rails_app/app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Courses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.name %>
        <td><%= link_to 'Show', course, class: 'btn btn-success' %></td>
        <td><%= link_to 'Edit', edit_course_path(course), class: 'btn btn-warning' %></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if current_user && can?(:create, Course) %>
  <%= link_to 'New Course', new_course_path, {class: 'btn btn-primary' } %>
<% end %>

test_rails_app/app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Back', courses_path %>

test_rails_app/app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>

test_rails_app/app/views/home/_student.html.erb
Name: <%= student.full_name %><br/>

test_rails_app/app/views/home/all_students.html.erb
<h1>Students list</h1>

<% @students.each do |student| %>
  <%= render partial: 'student', locals: { student: student } %>
<% end %>

test_rails_app/app/views/home/hello.html.erb
<h2>Hello!</h2>

test_rails_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestRailsApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <% if current_user %>
        Logged in as <%= current_user.email %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>